spring.application.name=springjdbcpostgres
spring.datasource.url=jdbc:postgresql://localhost:5432/student
spring.datasource.username=postgres
spring.datasource.password=Satyam@9334@
spring.datasource.driver-class-name=org.postgresql.Driver